"""Infrastructure as Code (IaC) Generator.

Stage 8: Generates deployment templates (Docker Compose, Terraform)
based on the required services specified in the runtime configuration.
"""

from __future__ import annotations

import logging
from datetime import datetime

from src.schemas.compilation import CompilationResult

logger = logging.getLogger(__name__)


class IaCGenerator:
    """Generates Infrastructure as Code (IaC) from the runtime config."""

    def generate(self, compilation: CompilationResult) -> dict[str, str]:
        """Generate IaC templates."""
        logger.info(f"Generating IaC templates for {compilation.id}")
        generated: dict[str, str] = {}

        if not compilation.runtime_config:
            return generated

        services = compilation.runtime_config.required_services or []
        services_lower = [s.lower() for s in services]

        generated["docker-compose.yml"] = self._generate_docker_compose(services_lower)
        generated["main.tf"] = self._generate_terraform(services_lower, compilation.db_schema.database_name if compilation.db_schema else "app_db")

        return generated

    def _generate_docker_compose(self, services: list[str]) -> str:
        """Generate a docker-compose.yml file."""
        lines = [
            "# Auto-generated by AI Application Compiler",
            f"# Generated at: {datetime.utcnow().isoformat()}",
            "version: '3.8'",
            "",
            "services:",
            "  api:",
            "    build: .",
            "    ports:",
            "      - '8000:8000'",
            "    environment:",
        ]

        if "postgres" in services or "postgresql" in services:
            lines.extend([
                "      - DATABASE_URL=postgresql://user:pass@db:5432/app_db",
                "    depends_on:",
                "      - db",
                "",
                "  db:",
                "    image: postgres:15-alpine",
                "    environment:",
                "      POSTGRES_USER: user",
                "      POSTGRES_PASSWORD: pass",
                "      POSTGRES_DB: app_db",
                "    ports:",
                "      - '5432:5432'",
                "    volumes:",
                "      - postgres_data:/var/lib/postgresql/data"
            ])

        if "redis" in services:
            lines.extend([
                "",
                "  redis:",
                "    image: redis:7-alpine",
                "    ports:",
                "      - '6379:6379'"
            ])

        lines.extend([
            "",
            "volumes:"
        ])
        if "postgres" in services or "postgresql" in services:
            lines.append("  postgres_data:")

        return "\n".join(lines)

    def _generate_terraform(self, services: list[str], db_name: str) -> str:
        """Generate a basic main.tf file for AWS."""
        lines = [
            "# Auto-generated by AI Application Compiler",
            f"# Generated at: {datetime.utcnow().isoformat()}",
            "terraform {",
            "  required_providers {",
            "    aws = {",
            "      source  = \"hashicorp/aws\"",
            "      version = \"~> 5.0\"",
            "    }",
            "  }",
            "}",
            "",
            "provider \"aws\" {",
            "  region = \"us-east-1\"",
            "}",
            "",
            "# Elastic Container Service (Fargate) for API",
            "resource \"aws_ecs_cluster\" \"app_cluster\" {",
            "  name = \"app-cluster\"",
            "}",
            ""
        ]

        if "postgres" in services or "postgresql" in services:
            lines.extend([
                "# RDS PostgreSQL Instance",
                "resource \"aws_db_instance\" \"app_db\" {",
                "  allocated_storage    = 20",
                "  engine               = \"postgres\"",
                "  engine_version       = \"15\"",
                "  instance_class       = \"db.t3.micro\"",
                f"  db_name              = \"{db_name}\"",
                "  username             = \"app_user\"",
                "  password             = \"CHANGE_ME_IN_SECRETS_MANAGER\"",
                "  skip_final_snapshot  = true",
                "}",
                ""
            ])

        if "redis" in services:
            lines.extend([
                "# ElastiCache Redis Cluster",
                "resource \"aws_elasticache_cluster\" \"app_cache\" {",
                "  cluster_id           = \"app-redis-cluster\"",
                "  engine               = \"redis\"",
                "  node_type            = \"cache.t3.micro\"",
                "  num_cache_nodes      = 1",
                "  parameter_group_name = \"default.redis7\"",
                "  engine_version       = \"7.0\"",
                "  port                 = 6379",
                "}",
                ""
            ])

        return "\n".join(lines)


# Singleton
iac_generator = IaCGenerator()
